### PR TITLE
Delete composer.lock

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
I don't see any benefit of having a lock file for a library, though perhaps this was added for a reason. This PR kinda is a question of why it was added :)

### CODE REVIEW

**Comment by gbirke** [comment]
The lock file ensures that the same version of the prod and dev dependencies (HTML Purifier) is used on all machines.

You could argue that semantic versioning protects against BC breaks, but as far as I understand semver, you can add new features in a minor release. So if the lock file is not checked in and a developer installs a newer minor version and uses the new features added in that version,  the tests/production code on all instances that did not update their version would break. And I don't think we have locked our dependencies to minor versions, just to major versions.

**Comment by JeroenDeDauw** [comment]
Sure, that's a good argument for having the lock file. You can just composer update when you run into an error after pulling new code, or perhaps always run composer update after doing that. The advantage of this approach is that you don't end up using old versions when you don't explicitly upgrade, and thus have a way to discover new features organically and also find bc breaks within a single major version early. Same for deprecations.

AFAIK PHP libraries generally don't include the lock file. Much bandwagon argument

**Comment by JeroenDeDauw** [comment]
@wiese what do you think?

**Comment by wiese** [comment]
Hi,
I get where you are coming from with the idea of removing the lock file - when using this project as a library in another project the file existence is irrelevant.
For development of the library itself however, I think it's important to have it for all the reasons you'd have it in a standalone project. Of course, this really only goes for the dev dependencies, but is important nonetheless.

Cheers

**Comment by JeroenDeDauw** [comment]
Ugggh. I think everyone using the exact same (and not latest version) is not an advantage in this situation. But whatever.

**Pull request closed without merging**
